// Generated by property/refresh-data.mjs — do not edit by hand.
const SWISS_PROPERTY_LIVE = {
    "updated": null,
    "source": "BFS Swiss Residential Property Price Index (IMPI) via opendata.swiss",
    "baselineQuarter": "2026-Q1",
    "latestQuarter": "2026-Q1",
    "factors": {
        "apartment": 1,
        "house": 1
    }
};
